# Generated by Django 5.1 on 2026-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
